In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [7]:
# create Dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1]) # no. of input in one row

# call model for forward pass
# model.forward(features) # we can use this but
model(features) # pytorch recommend this , # here  i sent all 10 rows corresponding to which i got y_pred for each row

tensor([[0.4317],
        [0.5093],
        [0.4467],
        [0.4552],
        [0.4108],
        [0.3916],
        [0.4854],
        [0.4838],
        [0.4100],
        [0.3552]], grad_fn=<SigmoidBackward0>)

In [11]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.4051, -0.2298,  0.3567,  0.1677,  0.2171]], requires_grad=True)

In [12]:
model.linear.bias

Parameter containing:
tensor([-0.3247], requires_grad=True)

In [13]:
!pip install torchinfo

In [14]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# making this NN complex

In [15]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [16]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.3822],
        [0.3952],
        [0.3733],
        [0.3841],
        [0.3895],
        [0.3911],
        [0.3900],
        [0.3762],
        [0.3986],
        [0.3896]], grad_fn=<SigmoidBackward0>)

In [17]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[ 0.3259, -0.1346,  0.2209, -0.2784,  0.2879],
        [ 0.2451,  0.1792,  0.0879, -0.0141, -0.2998],
        [-0.1406,  0.4453,  0.2656, -0.0023, -0.3248]], requires_grad=True)

In [18]:
model.linear2.weight

Parameter containing:
tensor([[0.1572, 0.3190, 0.3674]], requires_grad=True)

In [19]:
model.linear1.bias

Parameter containing:
tensor([ 0.0898, -0.3170, -0.0683], requires_grad=True)

In [20]:
model.linear2.bias

Parameter containing:
tensor([-0.5503], requires_grad=True)

In [21]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### another method: sequential containers

In [22]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [23]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass

model(features)

tensor([[0.3556],
        [0.3561],
        [0.3566],
        [0.3344],
        [0.3654],
        [0.3631],
        [0.3672],
        [0.3629],
        [0.3577],
        [0.3524]], grad_fn=<SigmoidBackward0>)

In [35]:
# show model weights and bias
print(model.network[0].weight)
print(model.network[0].bias)
print(model.network[2].weight)
print(model.network[2].bias)

Parameter containing:
tensor([[ 0.0531, -0.1586,  0.2474,  0.3424,  0.3680],
        [-0.3093,  0.1329, -0.4070, -0.1649, -0.0368],
        [-0.0383, -0.2025, -0.4024, -0.0663,  0.1328]], requires_grad=True)
Parameter containing:
tensor([0.0466, 0.3389, 0.3328], requires_grad=True)
Parameter containing:
tensor([[ 0.0136,  0.2499, -0.4309]], requires_grad=True)
Parameter containing:
tensor([-0.5677], requires_grad=True)


In [36]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00