In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.is_available(0)}") # here 0 means 1st one GPU
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


### Creating a Tensor



In [4]:
# using empty
a = torch.empty(2,3) # means we allocate a space for a 2x3 matrix

In [5]:
# Chech type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using rand
torch.rand(2,3) # creating a 2x3 matrix with random values between 0 and 1

tensor([[0.2132, 0.7167, 0.2213],
        [0.3948, 0.1816, 0.7477]])

### use of seed
- using manual_seed(r) any one can use the same matrix created by me using torch.rand(m,n)

In [11]:
# use of seed
torch.rand(2,3)

tensor([[0.2718, 0.8336, 0.8315],
        [0.3813, 0.1178, 0.9912]])

In [12]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
# using tensor ( we can create n-dim tensors)
torch.tensor([[1,2,3],
             [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [27]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
x.shape

torch.Size([2, 3])

In [30]:
torch.empty_like(x) # create a matrix of x shape

tensor([[133993975922048,       575319552, 133992845639024],
        [       11664816, 133992849126192, 133993968394352]])

In [32]:
torch.zeros_like(x) # create a zero matrix of x shape

tensor([[0, 0, 0],
        [0, 0, 0]])

In [33]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [35]:
torch.rand_like(x , dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor Data Types

In [36]:
# find data type
x.dtype

torch.int64

In [38]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [39]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [40]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### Mathematical operations

#### 1. Scalar operation

In [41]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [42]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

#### 2. Element wise operation

In [43]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [44]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [45]:
c = torch.tensor([1, -2, 3, -4])

In [46]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [47]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [48]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [49]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [52]:
# ceil
torch.ceil(d) # it will give least integer function(LIF)

tensor([2., 3., 4., 5.])

In [53]:
# floor
torch.floor(d) # it will give greatest integer function(GIF)

tensor([1., 2., 3., 4.])

In [55]:
# clamp
torch.clamp(d, min=2,max=3) # clamp will keep the value between 2 and 3

tensor([2.0000, 2.3000, 3.0000, 3.0000])

#### 3. Reduction operation

In [57]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [60]:
# sum
torch.sum(e) # it will give the sum of all the element

# sum along columns
torch.sum(e,dim=0)

# sum along rows
torch.sum(e, dim=1)

tensor([15., 13.])

In [63]:
# mean
torch.mean(e)

# mean along col
torch.mean(e, dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [64]:
# median
torch.median(e)


tensor(4.)

In [65]:
# min and max
torch.min(e)
torch.max(e)

tensor(9.)

In [66]:
# product
torch.prod(e)

tensor(0.)

In [67]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [68]:
# variance
torch.var(e)

tensor(9.8667)

In [71]:
# argmax
torch.argmax(e)

tensor(3)

In [72]:
# argmin
torch.argmin(e)

tensor(5)

#### 4. Matrix operations

In [73]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [74]:
# matrix multiplication
torch.matmul(f,g)

tensor([[116, 153],
        [166, 225]])

In [75]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [76]:
# transpose
torch.transpose(f,0,1) # it will transpose the columns with rows

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [79]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 0., 4.],
        [3., 8., 8.],
        [3., 3., 5.]])

In [80]:
# determinant
torch.det(h)

tensor(20.0000)

In [81]:
# inverse
torch.inverse(h)

tensor([[ 0.8000,  0.6000, -1.6000],
        [ 0.4500,  0.6500, -1.4000],
        [-0.7500, -0.7500,  2.0000]])

#### 5. Comparison operations

In [82]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 6, 4],
        [0, 8, 4]])
tensor([[7, 2, 3],
        [8, 5, 6]])


In [85]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[ True, False, False],
        [ True, False,  True]])

#### 6. Special functions

In [86]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 9., 5.],
        [0., 4., 2.]])

In [87]:
# log
torch.log(k)

tensor([[0.6931, 2.1972, 1.6094],
        [  -inf, 1.3863, 0.6931]])

In [88]:
# exp
torch.exp(k)

tensor([[7.3891e+00, 8.1031e+03, 1.4841e+02],
        [1.0000e+00, 5.4598e+01, 7.3891e+00]])

In [89]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 3.0000, 2.2361],
        [0.0000, 2.0000, 1.4142]])

In [92]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9999, 0.9933],
        [0.5000, 0.9820, 0.8808]])

In [98]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.8808, 0.9933, 0.9526],
        [0.1192, 0.0067, 0.0474]])

In [99]:
torch.relu(k)

tensor([[2., 9., 5.],
        [0., 4., 2.]])

### Inplace Operations

In [100]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])
tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])


In [102]:
m+n # it create new matrix

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [103]:
m.add_(n) # it will update the matrix m by adding m to n

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [104]:
m

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [105]:
n

tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])

In [107]:
m.relu_()

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [108]:
m

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

### Copying a Tensor

In [109]:
a = torch.rand(2,3)
a

tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [110]:
b = a

In [111]:
b

tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [112]:
# but if i will make updation in a the it will be reflect on b also

a[0][0] = 0

In [113]:
a

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [114]:
b

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [115]:
id(a)

133992880342032

In [116]:
id(b)

133992880342032

In [117]:
# so to get rid of this problem we will create a clone of a
b = a.clone()

In [118]:
a

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [119]:
b

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [120]:
a[0][0]=10

In [121]:
a

tensor([[10.0000,  0.4234,  0.5224],
        [ 0.4175,  0.0340,  0.9157]])

In [122]:
b

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [123]:
id(a)

133992880342032

In [124]:
id(b)

133992880347792